In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
train_df=pd.read_csv("C:/Users/Nagi/Documents/Hackathon/Train.csv")
test_df=pd.read_csv("C:/Users/Nagi/Documents/Hackathon/Test.csv")

In [5]:
train_df.head()

,date_time,is_holiday,air_pollution_index,humidity,wind_speed,wind_direction,visibility_in_miles,dew_point,temperature,rain_p_h,snow_p_h,clouds_all,weather_type,weather_description,traffic_volume
0,2012-10-02 09:00:00,None,121,89,2,329,1,1,288.28,0.0,0.0,40,Clouds,scattered clouds,5545
1,2012-10-02 10:00:00,None,178,67,3,330,1,1,289.36,0.0,0.0,75,Clouds,broken clouds,4516
2,2012-10-02 11:00:00,None,113,66,3,329,2,2,289.58,0.0,0.0,90,Clouds,overcast clouds,4767
3,2012-10-02 12:00:00,None,20,66,3,329,5,5,290.13,0.0,0.0,90,Clouds,overcast clouds,5026
4,2012-10-02 13:00:00,None,281,65,3,329,7,7,291.14,0.0,0.0,75,Clouds,broken clouds,4918

In [6]:
test_df.head()

,date_time,is_holiday,air_pollution_index,humidity,wind_speed,wind_direction,visibility_in_miles,dew_point,temperature,rain_p_h,snow_p_h,clouds_all,weather_type,weather_description
0,2017-05-18 00:00:00,None,73,63,1,27,4,4,285.15,0.0,0,90,Rain,moderate rain
1,2017-05-18 00:00:00,None,251,63,1,27,4,4,285.15,0.0,0,90,Mist,mist
2,2017-05-18 00:00:00,None,75,56,1,0,1,1,285.15,0.0,0,90,Drizzle,light intensity drizzle
3,2017-05-18 01:00:00,None,98,56,1,351,2,2,284.79,0.0,0,90,Rain,heavy intensity rain
4,2017-05-18 01:00:00,None,283,56,1,351,1,1,284.79,0.0,0,90,Mist,mist

In [7]:
train_df.isna().sum()

date_time              0
is_holiday             0
air_pollution_index    0
humidity               0
wind_speed             0
wind_direction         0
visibility_in_miles    0
dew_point              0
temperature            0
rain_p_h               0
snow_p_h               0
clouds_all             0
weather_type           0
weather_description    0
traffic_volume         0
dtype: int64

In [8]:
train_df.duplicated().sum()

0

In [9]:
train_df.columns.difference(test_df.columns)

Index(['traffic_volume'], dtype='object')

In [10]:
train_df["source"] = "train"
test_df["source"] = "test"
df = pd.concat([train_df,test_df])

C:\Users\Nagi\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

In [12]:
df.corr()

,air_pollution_index,clouds_all,dew_point,humidity,rain_p_h,snow_p_h,temperature,traffic_volume,visibility_in_miles,wind_direction,wind_speed
air_pollution_index,1.000000,-0.001816,0.004730,-0.000769,0.000417,0.006069,-0.002968,-0.003751,0.004730,0.002041,-0.002999
clouds_all,-0.001816,1.000000,-0.000573,0.012330,0.004818,0.027931,-0.101976,0.037922,-0.000573,0.012804,-0.002287
dew_point,0.004730,-0.000573,1.000000,0.009696,-0.006922,0.001163,0.001192,0.001348,1.000000,0.003188,-0.004173
humidity,-0.000769,0.012330,0.009696,1.000000,-0.009386,0.014305,0.019190,0.016455,0.009696,-0.073280,-0.165069
rain_p_h,0.000417,0.004818,-0.006922,-0.009386,1.000000,-0.000090,0.009069,0.005642,-0.006922,0.001858,0.000934
snow_p_h,0.006069,0.027931,0.001163,0.014305,-0.000090,1.000000,-0.019755,0.001197,0.001163,-0.000541,-0.006223
temperature,-0.002968,-0.101976,0.001192,0.019190,0.009069,-0.019755,1.000000,0.127871,0.001192,0.008194,0.000286
traffic_volume,-0.003751,0.037922,0.001348,0.016455,0.005642,0.001197,0.127871,1.000000,0.001348,0.014278,0.016329
visibility_in_miles,0.004730,-0.000573,1.000000,0.009696,-0.006922,0.001163,0.001192,0.001348,1.000000,0.003188,-0.004173
wind_direction,0.002041,0.012804,0.003188,-0.073280,0.001858,-0.000541,0.008194,0.014278,0.003188,1.000000,0.171938
wind_speed,-0.002999,-0.002287,-0.004173,-0.165069,0.000934,-0.006223,0.000286,0.016329,-0.004173,0.171938,1.000000

In [11]:
# Identify discrete and continous columns
col_disc=[]
col_medium=[]
col_cont=[]
print("Attributes with their distinct count and their classification")
for i in df.columns:
    if df[i].nunique() <=10:
        print(i,"==",df[i].nunique(),"== disc")
        col_disc.append(i)
    elif (df[i].nunique() >10 and df[i].nunique() <100):
        col_medium.append(i)    
        print(i,"==",df[i].nunique(),"== medium")
    else:
        col_cont.append(i)
        print(i,"==",df[i].nunique(),"== cont")

Attributes with their distinct count and their classification
air_pollution_index == 290 == cont
clouds_all == 60 == medium
date_time == 40575 == cont
dew_point == 9 == disc
humidity == 91 == medium
is_holiday == 12 == medium
rain_p_h == 372 == cont
snow_p_h == 12 == medium
source == 2 == disc
temperature == 5843 == cont
traffic_volume == 6462 == cont
visibility_in_miles == 9 == disc
weather_description == 38 == medium
weather_type == 11 == medium
wind_direction == 361 == cont
wind_speed == 17 == medium

In [14]:
col_cont_key_df=df[col_cont]
num_cont_list=col_cont_key_df.columns.drop("date_time")

In [16]:
df.weather_type.unique()

array(['Clouds', 'Clear', 'Rain', 'Drizzle', 'Mist', 'Haze', 'Fog',
       'Thunderstorm', 'Snow', 'Squall', 'Smoke'], dtype=object)

In [17]:
df.is_holiday.unique()

array(['None', 'Columbus Day', 'Veterans Day', 'Thanksgiving Day',
       'Christmas Day', 'New Years Day', 'Washingtons Birthday',
       'Memorial Day', 'Independence Day', 'State Fair', 'Labor Day',
       'Martin Luther King Jr Day'], dtype=object)

In [18]:
df.head()

,air_pollution_index,clouds_all,date_time,dew_point,humidity,is_holiday,rain_p_h,snow_p_h,source,temperature,traffic_volume,visibility_in_miles,weather_description,weather_type,wind_direction,wind_speed
0,121,40,2012-10-02 09:00:00,1,89,None,0.0,0.0,train,288.28,5545.0,1,scattered clouds,Clouds,329,2
1,178,75,2012-10-02 10:00:00,1,67,None,0.0,0.0,train,289.36,4516.0,1,broken clouds,Clouds,330,3
2,113,90,2012-10-02 11:00:00,2,66,None,0.0,0.0,train,289.58,4767.0,2,overcast clouds,Clouds,329,3
3,20,90,2012-10-02 12:00:00,5,66,None,0.0,0.0,train,290.13,5026.0,5,overcast clouds,Clouds,329,3
4,281,75,2012-10-02 13:00:00,7,65,None,0.0,0.0,train,291.14,4918.0,7,broken clouds,Clouds,329,3

In [19]:
df.weather_type.unique()

array(['Clouds', 'Clear', 'Rain', 'Drizzle', 'Mist', 'Haze', 'Fog',
       'Thunderstorm', 'Snow', 'Squall', 'Smoke'], dtype=object)

In [24]:
# one-hot encoding
cat_col=['weather_type','is_holiday','weather_description']
one_hot=pd.get_dummies(df[cat_col])
traffic_vol_procsd_df=pd.concat([df,one_hot],axis=1)
traffic_vol_procsd_df.head(10)

,air_pollution_index,clouds_all,date_time,dew_point,humidity,is_holiday,rain_p_h,snow_p_h,source,temperature,...,weather_description_sleet,weather_description_smoke,weather_description_snow,weather_description_thunderstorm,weather_description_thunderstorm with drizzle,weather_description_thunderstorm with heavy rain,weather_description_thunderstorm with light drizzle,weather_description_thunderstorm with light rain,weather_description_thunderstorm with rain,weather_description_very heavy rain
0,121,40,2012-10-02 09:00:00,1,89,None,0.0,0.0,train,288.28,...,0,0,0,0,0,0,0,0,0,0
1,178,75,2012-10-02 10:00:00,1,67,None,0.0,0.0,train,289.36,...,0,0,0,0,0,0,0,0,0,0
2,113,90,2012-10-02 11:00:00,2,66,None,0.0,0.0,train,289.58,...,0,0,0,0,0,0,0,0,0,0
3,20,90,2012-10-02 12:00:00,5,66,None,0.0,0.0,train,290.13,...,0,0,0,0,0,0,0,0,0,0
4,281,75,2012-10-02 13:00:00,7,65,None,0.0,0.0,train,291.14,...,0,0,0,0,0,0,0,0,0,0
5,23,1,2012-10-02 14:00:00,6,65,None,0.0,0.0,train,291.72,...,0,0,0,0,0,0,0,0,0,0
6,184,1,2012-10-02 15:00:00,7,64,None,0.0,0.0,train,293.17,...,0,0,0,0,0,0,0,0,0,0
7,167,1,2012-10-02 16:00:00,7,64,None,0.0,0.0,train,293.86,...,0,0,0,0,0,0,0,0,0,0
8,119,20,2012-10-02 17:00:00,6,63,None,0.0,0.0,train,294.14,...,0,0,0,0,0,0,0,0,0,0
9,161,20,2012-10-02 18:00:00,3,63,None,0.0,0.0,train,293.10,...,0,0,0,0,0,0,0,0,0,0

In [25]:
df.weather_description.unique()

array(['scattered clouds', 'broken clouds', 'overcast clouds',
       'sky is clear', 'few clouds', 'light rain',
       'light intensity drizzle', 'mist', 'haze', 'fog',
       'proximity shower rain', 'drizzle', 'moderate rain',
       'heavy intensity rain', 'proximity thunderstorm',
       'thunderstorm with light rain', 'proximity thunderstorm with rain',
       'heavy snow', 'heavy intensity drizzle', 'snow',
       'thunderstorm with heavy rain', 'freezing rain', 'shower snow',
       'light rain and snow', 'light intensity shower rain', 'SQUALLS',
       'thunderstorm with rain', 'proximity thunderstorm with drizzle',
       'thunderstorm', 'Sky is Clear', 'very heavy rain',
       'thunderstorm with light drizzle', 'light snow',
       'thunderstorm with drizzle', 'smoke', 'shower drizzle',
       'light shower snow', 'sleet'], dtype=object)

In [23]:
df.shape

(48204, 16)

In [26]:
traffic_dt_df=traffic_vol_procsd_df.drop(columns=['weather_type','is_holiday','weather_description'])
traffic_dt_df.set_index('date_time',inplace=True)
traffic_dt_df.head(10)

,air_pollution_index,clouds_all,dew_point,humidity,rain_p_h,snow_p_h,source,temperature,traffic_volume,visibility_in_miles,...,weather_description_sleet,weather_description_smoke,weather_description_snow,weather_description_thunderstorm,weather_description_thunderstorm with drizzle,weather_description_thunderstorm with heavy rain,weather_description_thunderstorm with light drizzle,weather_description_thunderstorm with light rain,weather_description_thunderstorm with rain,weather_description_very heavy rain
date_time,,,,,,,,,,,,,,,,,,,,,
2012-10-02 09:00:00,121,40,1,89,0.0,0.0,train,288.28,5545.0,1,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 10:00:00,178,75,1,67,0.0,0.0,train,289.36,4516.0,1,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 11:00:00,113,90,2,66,0.0,0.0,train,289.58,4767.0,2,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 12:00:00,20,90,5,66,0.0,0.0,train,290.13,5026.0,5,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 13:00:00,281,75,7,65,0.0,0.0,train,291.14,4918.0,7,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 14:00:00,23,1,6,65,0.0,0.0,train,291.72,5181.0,6,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 15:00:00,184,1,7,64,0.0,0.0,train,293.17,5584.0,7,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 16:00:00,167,1,7,64,0.0,0.0,train,293.86,6015.0,7,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 17:00:00,119,20,6,63,0.0,0.0,train,294.14,5791.0,6,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 18:00:00,161,20,3,63,0.0,0.0,train,293.10,4770.0,3,...,0,0,0,0,0,0,0,0,0,0

In [27]:
train_final = traffic_dt_df[traffic_dt_df.source=="train"]
test_final = traffic_dt_df[traffic_dt_df.source=="test"]

In [28]:
train_final.drop(columns="source",inplace=True)
test_final.drop(columns="source",inplace=True)

C:\Users\Nagi\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [29]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression


#split train data
train_X = train_final.drop(columns=["traffic_volume"])
train_Y = train_final["traffic_volume"]
test_X = test_final.drop(columns=["traffic_volume"])
test_Y = test_final["traffic_volume"]

In [31]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import cross_val_score, train_test_split, StratifiedKFold
m = RandomForestRegressor(n_jobs = -1)
m.fit(train_X, train_Y)

C:\Users\Nagi\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [36]:
from sklearn.feature_selection import SelectFromModel
sel = SelectFromModel(RandomForestRegressor(n_estimators = 100))
sel.fit(train_X, train_Y)

SelectFromModel(estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [38]:
sel.get_support()

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [39]:
selected_feat= train_X.columns[(sel.get_support())]
len(selected_feat)

9

In [40]:
selected_feat

Index(['air_pollution_index', 'clouds_all', 'dew_point', 'humidity',
       'rain_p_h', 'temperature', 'visibility_in_miles', 'wind_direction',
       'wind_speed'],
      dtype='object')

In [53]:
df_selected_feat = df[['air_pollution_index', 'clouds_all', 'dew_point', 'humidity',
       'rain_p_h', 'temperature', 'visibility_in_miles', 'wind_direction',
       'wind_speed','traffic_volume','source','date_time']]

In [54]:
df_selected_feat.set_index('date_time',inplace=True)
df_selected_feat.head(10)

,air_pollution_index,clouds_all,dew_point,humidity,rain_p_h,temperature,visibility_in_miles,wind_direction,wind_speed,traffic_volume,source
date_time,,,,,,,,,,,
2012-10-02 09:00:00,121,40,1,89,0.0,288.28,1,329,2,5545.0,train
2012-10-02 10:00:00,178,75,1,67,0.0,289.36,1,330,3,4516.0,train
2012-10-02 11:00:00,113,90,2,66,0.0,289.58,2,329,3,4767.0,train
2012-10-02 12:00:00,20,90,5,66,0.0,290.13,5,329,3,5026.0,train
2012-10-02 13:00:00,281,75,7,65,0.0,291.14,7,329,3,4918.0,train
2012-10-02 14:00:00,23,1,6,65,0.0,291.72,6,328,3,5181.0,train
2012-10-02 15:00:00,184,1,7,64,0.0,293.17,7,328,3,5584.0,train
2012-10-02 16:00:00,167,1,7,64,0.0,293.86,7,327,3,6015.0,train
2012-10-02 17:00:00,119,20,6,63,0.0,294.14,6,327,3,5791.0,train
2012-10-02 18:00:00,161,20,3,63,0.0,293.10,3,326,3,4770.0,train

In [48]:
traffic_dt_df.head()

,air_pollution_index,clouds_all,dew_point,humidity,rain_p_h,snow_p_h,source,temperature,traffic_volume,visibility_in_miles,...,weather_description_sleet,weather_description_smoke,weather_description_snow,weather_description_thunderstorm,weather_description_thunderstorm with drizzle,weather_description_thunderstorm with heavy rain,weather_description_thunderstorm with light drizzle,weather_description_thunderstorm with light rain,weather_description_thunderstorm with rain,weather_description_very heavy rain
date_time,,,,,,,,,,,,,,,,,,,,,
2012-10-02 09:00:00,121,40,1,89,0.0,0.0,train,288.28,5545.0,1,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 10:00:00,178,75,1,67,0.0,0.0,train,289.36,4516.0,1,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 11:00:00,113,90,2,66,0.0,0.0,train,289.58,4767.0,2,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 12:00:00,20,90,5,66,0.0,0.0,train,290.13,5026.0,5,...,0,0,0,0,0,0,0,0,0,0
2012-10-02 13:00:00,281,75,7,65,0.0,0.0,train,291.14,4918.0,7,...,0,0,0,0,0,0,0,0,0,0

In [55]:
train_final = df_selected_feat[df_selected_feat.source=="train"]
test_final = df_selected_feat[df_selected_feat.source=="test"]

In [56]:
train_final.drop(columns="source",inplace=True)
test_final.drop(columns="source",inplace=True)

C:\Users\Nagi\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [57]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression


#split train data
train_X = train_final.drop(columns=["traffic_volume"])
train_Y = train_final["traffic_volume"]
test_X = test_final.drop(columns=["traffic_volume"])
test_Y = test_final["traffic_volume"]

In [58]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import cross_val_score, train_test_split, StratifiedKFold
m = RandomForestRegressor(n_jobs = -1)
m.fit(train_X, train_Y)

C:\Users\Nagi\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [59]:
dtrain_predictions = m.predict(train_X)
dtrain_predictions

array([4834.9, 4130.6, 4787.2, ..., 1784.9, 1621.6, 1437.3])

In [61]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score
#Print model report:
print("\nModel Report")
print("RMSE : %.4g" % np.sqrt(mean_squared_error(train_Y.values, dtrain_predictions)))
    
#Predict on testing data:
test_final["res_random_forest"] =  m.predict(test_X)

Model Report
RMSE : 787.5

C:\Users\Nagi\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [12]:
df.dtypes

air_pollution_index      int64
clouds_all               int64
date_time               object
dew_point                int64
humidity                 int64
is_holiday              object
rain_p_h               float64
snow_p_h               float64
source                  object
temperature            float64
traffic_volume         float64
visibility_in_miles      int64
weather_description     object
weather_type            object
wind_direction           int64
wind_speed               int64
dtype: object

In [13]:
# one-hot encoding
cat_col=['weather_type','is_holiday','weather_description']
one_hot=pd.get_dummies(df[cat_col])
traffic_vol_procsd_df=pd.concat([df,one_hot],axis=1)
traffic_vol_procsd_df.head(10)

,air_pollution_index,clouds_all,date_time,dew_point,humidity,is_holiday,rain_p_h,snow_p_h,source,temperature,...,weather_description_sleet,weather_description_smoke,weather_description_snow,weather_description_thunderstorm,weather_description_thunderstorm with drizzle,weather_description_thunderstorm with heavy rain,weather_description_thunderstorm with light drizzle,weather_description_thunderstorm with light rain,weather_description_thunderstorm with rain,weather_description_very heavy rain
0,121,40,2012-10-02 09:00:00,1,89,None,0.0,0.0,train,288.28,...,0,0,0,0,0,0,0,0,0,0
1,178,75,2012-10-02 10:00:00,1,67,None,0.0,0.0,train,289.36,...,0,0,0,0,0,0,0,0,0,0
2,113,90,2012-10-02 11:00:00,2,66,None,0.0,0.0,train,289.58,...,0,0,0,0,0,0,0,0,0,0
3,20,90,2012-10-02 12:00:00,5,66,None,0.0,0.0,train,290.13,...,0,0,0,0,0,0,0,0,0,0
4,281,75,2012-10-02 13:00:00,7,65,None,0.0,0.0,train,291.14,...,0,0,0,0,0,0,0,0,0,0
5,23,1,2012-10-02 14:00:00,6,65,None,0.0,0.0,train,291.72,...,0,0,0,0,0,0,0,0,0,0
6,184,1,2012-10-02 15:00:00,7,64,None,0.0,0.0,train,293.17,...,0,0,0,0,0,0,0,0,0,0
7,167,1,2012-10-02 16:00:00,7,64,None,0.0,0.0,train,293.86,...,0,0,0,0,0,0,0,0,0,0
8,119,20,2012-10-02 17:00:00,6,63,None,0.0,0.0,train,294.14,...,0,0,0,0,0,0,0,0,0,0
9,161,20,2012-10-02 18:00:00,3,63,None,0.0,0.0,train,293.10,...,0,0,0,0,0,0,0,0,0,0

In [21]:
numeric_df = df.select_dtypes(include=[np.number])
numeric_df

,air_pollution_index,clouds_all,dew_point,humidity,rain_p_h,snow_p_h,temperature,traffic_volume,visibility_in_miles,wind_direction,wind_speed
0,121,40,1,89,0.00,0.0,288.28,5545.0,1,329,2
1,178,75,1,67,0.00,0.0,289.36,4516.0,1,330,3
2,113,90,2,66,0.00,0.0,289.58,4767.0,2,329,3
3,20,90,5,66,0.00,0.0,290.13,5026.0,5,329,3
4,281,75,7,65,0.00,0.0,291.14,4918.0,7,329,3
5,23,1,6,65,0.00,0.0,291.72,5181.0,6,328,3
6,184,1,7,64,0.00,0.0,293.17,5584.0,7,328,3
7,167,1,7,64,0.00,0.0,293.86,6015.0,7,327,3
8,119,20,6,63,0.00,0.0,294.14,5791.0,6,327,3
9,161,20,3,63,0.00,0.0,293.10,4770.0,3,326,3
10,243,20,8,62,0.00,0.0,290.97,3539.0,8,326,3
11,150,1,5,62,0.00,0.0,289.38,2784.0,5,326,3
12,128,1,4,61,0.00,0.0,288.61,2361.0,4,325,4
13,18,1,7,61,0.00,0.0,287.16,1529.0,7,325,4
14,186,1,5,60,0.00,0.0,285.45,963.0,5,324,4
15,58,1,2,60,0.00,0.0,284.63,506.0,2,324,4
16,158,1,6,59,0.00,0.0,283.47,321.0,6,324,4
17,166,1,1,59,0.00,0.0,281.18,273.0,1,323,4
18,101,1,7,58,0.00,0.0,281.09,367.0,7,323,4
19,161,1,4,58,0.00,0.0,279.53,814.0,4,322,4
20,179,1,3,57,0.00,0.0,278.62,2718.0,3,322,4
21,93,1,4,57,0.00,0.0,278.23,5673.0,4,322,4
22,57,1,4,56,0.00,0.0,278.12,6511.0,4,321,4
23,226,1,4,56,0.00,0.0,282.48,5471.0,4,321,4
24,86,1,3,55,0.00,0.0,291.97,5097.0,3,320,4
25,52,1,1,55,0.00,0.0,293.23,4887.0,1,320,4
26,273,1,4,55,0.00,0.0,294.31,5337.0,4,320,4
27,72,1,3,55,0.00,0.0,295.17,5692.0,3,350,5
28,254,1,1,55,0.00,0.0,295.13,6137.0,1,320,4
29,129,20,4,55,0.00,0.0,293.66,4623.0,4,330,5
...,...,...,...,...,...,...,...,...,...,...,...
14424,19,90,4,97,0.00,0.0,280.55,NaN,4,327,2
14425,251,90,6,74,0.00,0.0,280.40,NaN,6,168,7
14426,273,90,8,88,0.00,0.0,280.54,NaN,8,273,8
14427,207,90,7,97,0.00,0.0,280.32,NaN,7,210,0
14428,266,90,9,81,0.00,0.0,280.30,NaN,9,156,5
14429,290,90,2,96,0.00,0.0,280.19,NaN,2,187,6
14430,184,90,9,92,0.00,0.0,280.07,NaN,9,169,8
14431,276,90,4,10,0.00,0.0,280.08,NaN,4,271,8
14432,199,90,2,52,0.00,0.0,279.88,NaN,2,138,7
14433,224,90,6,44,0.00,0.0,279.96,NaN,6,219,1
14434,49,90,9,76,0.00,0.0,280.17,NaN,9,179,7
14435,80,90,3,67,0.00,0.0,280.16,NaN,3,286,5
14436,228,90,9,16,0.00,0.0,280.28,NaN,9,321,4
14437,14,90,4,80,0.00,0.0,280.62,NaN,4,208,2
14438,234,75,2,12,0.00,0.0,281.38,NaN,2,265,5
14439,194,90,1,22,0.00,0.0,282.18,NaN,1,266,7
14440,153,75,4,14,0.00,0.0,282.69,NaN,4,283,8
14441,191,90,9,10,0.00,0.0,283.03,NaN,9,321,3
14442,225,90,5,44,0.00,0.0,283.48,NaN,5,344,8
14443,199,90,8,86,0.00,0.0,283.48,NaN,8,302,2
14444,272,75,3,18,0.00,0.0,283.84,NaN,3,188,1
14445,86,75,3,33,0.00,0.0,283.84,NaN,3,294,4
14446,60,75,8,71,0.00,0.0,284.38,NaN,8,168,6
14447,133,75,7,37,0.00,0.0,284.79,NaN,7,346,1
14448,133,75,4,25,0.25,0.0,284.20,NaN,4,227,5
14449,176,75,4,21,0.00,0.0,283.45,NaN,4,345,4
14450,214,90,6,95,0.00,0.0,282.76,NaN,6,280,8
14451,173,90,1,63,0.00,0.0,282.73,NaN,1,238,4
14452,21,90,7,57,0.00,0.0,282.09,NaN,7,268,8
14453,116,90,6,70,0.00,0.0,282.12,NaN,6,328,8

In [24]:
from sklearn.preprocessing import StandardScaler
scaled_df = StandardScaler().fit_transform(numeric_df)
scaled_df

C:\Users\Nagi\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Nagi\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

array([[-0.40405157, -0.23996279, -1.55133786, ..., -1.55133786,
         1.2849485 , -0.68687773],
       [ 0.27748157,  0.65712012, -1.55133786, ..., -1.55133786,
         1.29509933, -0.21215152],
       [-0.49970534,  1.04158422, -1.16296761, ..., -1.16296761,
         1.2849485 , -0.21215152],
       ...,
       [ 0.21769796,  1.04158422, -1.55133786, ..., -1.55133786,
         0.36122307,  0.26257469],
       [-1.59972374,  1.04158422,  0.77888359, ...,  0.77888359,
         0.66574794,  2.16147952],
       [-0.46383518,  1.04158422,  0.39051335, ...,  0.39051335,
         1.27479767,  2.16147952]])

In [40]:
scaled_pd_df = pd.DataFrame(data=scaled_df[1:,1:],    # values
...              columns=scaled_df[0,1:])
final_df = pd.concat([one_hot,scaled_pd_df],axis=1)
#final_df.set_index('date_time',inplace=True)
final_df

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [34]:
type(scaled_df)

numpy.ndarray

In [35]:
type(one_hot)

pandas.core.frame.DataFrame